### ISSUE TITLE
Configuration with complex json object

### ISSUE THREAD

**Issue by uncodead** [rjwats/esp8266-react#1]
I have a configuration like that:

Data/config/foo.json
{
   "Foo": [
        { "name":"test 1", "qnt":1},
        { "name":"test 2", "qnt": 2}
    ]
}

How do i need to declare my property in the service class to read and write this json object?

Thank you

**Comment by rjwats** [comment]
The framework uses arduinojson, which itself has excellent documentation here:

https://arduinojson.org/v5/doc/

You will need to use JsonArray's .size() function to iterate over the "Foo" array. It will look something like this:

`
void MyService::readFromJsonObject(JsonObject& root) {
    JsonArray& fooArr = root["Foo"];    
    for (int i = 0; i < fooArr.size(); i++){
      JsonObject& fooObj =  fooArr[i];
      // Do something with fooObj["name"] and fooObj["qnt"]
    }
}
`

You can also interrogate the contents of an object - in the case where you don't want to blindly trust it:

`
if (root["Foo"].is<JsonArray&>()){
  // parse the array as above...
}
`

You can use the createNestedArray(TString* key) function to create an array in your write function. See WiFiScanner.cpp (listNetworks function) for an example of how to create a nested array of objects - a similar structure to your requirement.

Hope this helps.
