### ISSUE TITLE
WWWData not found

### ISSUE THREAD

**Issue by dfcoutinho** [rjwats/esp8266-react#108]
The compiler stop Always on this missing lib: #include <WWWData.h> 
This library is not in the lib directory and I did not find it to install.

**Comment by rjwats** [comment]
Can you confirm that you have the prerequisites installed and that you are
following the build instructions on in the README?

https://github.com/rjwats/esp8266-react#prerequisites

WWWData.h is created during the build process assuming everything is
configured correctly.

Can you confirm what Operating System you are using and provide the console
output of the build process and I'll see if I can help.

**Comment by rjwats** [comment]
Closing this because of no response. If you are still having problems feel free to re-open.
