### ISSUE TITLE
Looks like link broken. https://github.com/rjwats/esp8266-react/blob/master/data

### ISSUE THREAD

**Issue by tichaonax** [rjwats/esp8266-react#125]
I downloaded the latest master today, builds fine but does not deploy the web UI. It looks like the data folder is missing in the latest master pull. https://github.com/rjwats/esp8266-react/blob/master/data

Building SPIFFS image from 'data' directory to .pio/build/esp12e/spiffs.bin
warning: can't read source directory
*** [.pio/build/esp12e/spiffs.bin] Error 1

If I am wrong please help resolve the issue for me.
Excellent work please keep it up,I really love this.

**Comment by rjwats** [comment]
Hi Tichaona,

The data folder is indeed missing now. I'll remove the references from the
README.

A recent change means that the UI is packaged in the build process and
served from PROGMEM. So unless you've disabled the -PROGMEM_WWW flag that
data folder won't exist and you will not need to perform the file system
image upload step.

Here are the docs about the change:

https://github.com/rjwats/esp8266-react#building--uploading-the-interface

You may be interested in the Factory Settings feature which was another
recent change:

https://github.com/rjwats/esp8266-react#factory-settings

Let me know if you are still having issues.
