### ISSUE TITLE
'NTPStatus' is not a class, namespace, or enumeration

### ISSUE THREAD

**Issue by waltercassiano** [rjwats/esp8266-react#13]
Hi 

I got this error when I tried build.

**Comment by atsteen** [comment]
Hello Walter, what IDE are you using?  VSCode, Atom, other?  Perhaps share the verbose build log output with us?  Thanks.

**Comment by waltercassiano** [comment]
Hello @atsteen 

I'm using VSCode. 
I change on platformio.ini the Lib NtpClient to https://github.com/gmag11/NtpClient#2.5.1 and it works.

So, I'll share later.
 
Thanks

**Comment by rjwats** [comment]
Looks like the NtpClient is being updated to work with non-blocking APIs, however it has an additional dependency which is not yet documented and is released at the moment as 3.0.0 beta. I'm going to update the dependencies in platformio.ini to lock to versions which should resolve this.

**Comment by rjwats** [comment]
Latest commit should fix the build issues - have tested fresh builds for ESP32 and ESP8266 under VSCode.

Would you mind testing if this works for you?

**Comment by waltercassiano** [comment]
Hi 

Nice, it works

tks

**Comment by rjwats** [comment]
Thanks Walter, I'm closing the issue.
