### ISSUE TITLE
Migrate steps

### ISSUE THREAD

**Issue by uncodead** [rjwats/esp8266-react#138]
Hi @rjwats 

As you know i'm using a old framework version - without MQTT, Websocket, typescript and others.

I'm afraid to refactor all my views and brackend server to the new framework format. Is there a easy way to migrate my project?

Thanks for all!

**Comment by rjwats** [comment]
Hey Bruno, nice to hear from you again.

Like you say, there have been some significant changes to the framework.
Any upgrade will probably be a bit involved but most of your code should be
adaptable with a little bit of effort. I think it's best to read the latter
part of the README regarding developing with the framework as a starting
point. It is event driven now and the "StatefulService" class is
responsible for managing state and observing state changes - that's the
most important concept to understand. You might find you can use some of
the new features to improve your project.

I know you mentioned in the past wanting to be able to disable certain
features at build time (authentication IIRC). Features such as MQTT might
just be "baggage" if you don't intend to use them in your project. I am
working on that and also on improving the logging at the moment. (Replacing
Serial.print calls with macros so logs can be sent to multiple targets
(filesystem/websockets/serial) or disabled etc...)

Let me know if you have any specific questions when you start looking at
this, happy to help.

**Comment by uncodead** [comment]
Thanks!
