### ISSUE TITLE
RestController Support: Updating a single value in nested JSON

### ISSUE THREAD

**Issue by tichaonax** [rjwats/esp8266-react#139]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/1031407/83335611-a87e2700-a273-11ea-8774-75d35356bd63.png">

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1031407/83335685-0b6fbe00-a274-11ea-90d0-245048abe5c7.png">

The RestController works great for root level attributes. I ran into an issue when wanting to update the runEvery nested attribute. I had to cheat as you see in the image writing back to the event object by calling my own form event handler and repackage the event object to play nice with the RestController handleValueChange method as it can accepted a single object.

Its a nice to have but for now I do have a workaround.

**Comment by rjwats** [comment]
I probably would have chosen to do that slightly differently. You could write a simple wrapper which uses the extractEventValue helper which would work for any of your schedule values:

```typescript
      handleScheduleValueChange = (name: keyof Schedule) => (event: React.ChangeEvent<HTMLInputElement>) => {
        const { data, setData } = props;
        setData({ ...data, schedule: {...data.schedule, [name]: extractEventValue(event) } });
      }
```

**Comment by tichaonax** [comment]
But I do not want to modify the framework files. Your solution seems to suggest I put my change there which could be overwritten with your future updates. My workaround is all in my code that I control. Unless I am missing something. I like your suggestion however.

**Comment by tichaonax** [comment]
OK I see what you mean now that is my callbak func, I will use that approach instead.

**Comment by tichaonax** [comment]
That worked beutifull, I am using a Select box so had to change
(event: React.ChangeEvent<HTMLInputElement>) => 
  to
(event: any) =>
This is exactly what I wanted, thanks for a quick suggestion and better solutoon.
