### ISSUE TITLE
JWT with RSA algorithm

### ISSUE THREAD

**Issue by uncodead** [rjwats/esp8266-react#155]
Is it possible make JWT with RSA algorithm (public and private keys)?

**Comment by rjwats** [comment]
I'm sure it's possible - though in my understanding RSA is way more memory
hungry - so that will be interesting.

Out of curiosity, what is the requirement?

**Comment by uncodead** [comment]
Avoid secret keys inside project... we'll have only a plublic key inside project.

Thks

**Comment by rjwats** [comment]
The secret can be overridden on the device once flashed and by default it
now uses the chip id (different devices get different-ish default secrets).
So it's not awful in that regard.

I think without SSL on the HTTP endpoints security is somewhat flawed
anyway. When I last looked at this it looked unfeasible as TLS required
~15k of RAM per request at a minimum.

I think the security can be described as "best effort", not "enterprise
grade". Designed to stop the casual person who discovers the devices on the
network :)

On this subject, I've been pondering if JWT expiry and a token generator in
the UI might be worth implementing though. So you can generate tokens for
interfacing with the device externally.

**Comment by uncodead** [comment]
JWT expiry is the best for now...

**Comment by uncodead** [comment]
Changing the subject, have you managed to make https requests on esp8266? I am suffering!

**Comment by rjwats** [comment]
It's not something I've tried. I did try to get TLS working on MQTT... it
"worked" but was really impractical due to the memory requirements.

I'm sure you'll have similar problems with https, it's probably possible if
it's just about the only thing the device is doing.

What are you trying to do exactly?

**Comment by uncodead** [comment]
i need to call an api (https://brewuno.com/api/) but inside my project it isnt connecting.
when i create a project from scratch works. i'm supposing is a issue inside wifisettins.cpp.

**Comment by rjwats** [comment]
Pretty sure you need to be thinking about this as a memory issue:

- Getting HTTP working seems to be trivial in a loop() function
- When switching the same code to use HTTPS - using BearSSL::WiFiClientSecure as the client the client returns "connection refused"
- I managed to get HTTPS "working" after stripping features out of the framework till there was enough memory available to service the request

It looks like you'll need about @ 30k of free heap to make this work:

![image](https://user-images.githubusercontent.com/1330772/85197246-b73a8580-b2d7-11ea-9457-c28358b11c89.png)

During the request the available heap drops significantly:

![image](https://user-images.githubusercontent.com/1330772/85197503-44caa500-b2d9-11ea-9f96-78449aefd5f5.png)

Adding some memory metrics to [this example](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/examples/BasicHttpsClient/BasicHttpsClient.ino), you can see that the HTTPS request is incredibly memory hungry:

![image](https://user-images.githubusercontent.com/1330772/85197680-7c861c80-b2da-11ea-95bf-7486083452c2.png)

So yeah... it needs 28,816 bytes for the request!

**Comment by rjwats** [comment]
I can also confirm I have no issues connecting to HTTPS services on my ESP32 boards - more RAM available here:

![image](https://user-images.githubusercontent.com/1330772/85199746-caeee780-b2e9-11ea-9a85-6f4d05e19db0.png)

**Comment by uncodead** [comment]
it was a memory issue! thanks!
