### ISSUE TITLE
Report PSRAM on status screen for ESP32

### ISSUE THREAD

**Issue by rjwats** [rjwats/esp8266-react#158]

**Comment by proddy** [comment]
side note: for older ESP32 boards (rev0 or rev1) you have to add ` -mfix-esp32-psram-cache-issue` to the build flags in `platformio.ini`

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html#esp32-rev-v1
https://thingpulse.com/esp32-how-to-use-psram/
