### ISSUE TITLE
Migrating to ArduinoJson6

### ISSUE THREAD

**Issue by uncodead** [rjwats/esp8266-react#16]
Hi, i'm planning to migrate my project to framework's new version, but i've some classes with attributes like this:

JsonObject *_mashSettings;

How can i migrate in this case (Arduinojson6)? See exemples:

https://github.com/uncodead/biabrewex/blob/master/src/MashService.cpp
https://github.com/uncodead/biabrewex/blob/master/src/MashService.h

the screen of this code:
![WhatsApp Image 2019-03-24 at 14 02 27](https://user-images.githubusercontent.com/181846/56844293-50147300-6884-11e9-92d7-0df07112c111.jpeg)

Whats the best way to migrate this code? Can you help-me?

**Comment by rjwats** [comment]
See the following diff: https://github.com/rjwats/esp8266-react/commit/e68b7627f2751f5366ab3870709a0bdffe0ad7de

The diff of SettingsPersistence.h demonstrates most of the changes required to work with the new ArduinoJson v6 APIs.

There is an upgrade guide on the ArduinoJson which explains how to use the new MemberProxy objects:

https://arduinojson.org/v6/doc/upgrade/

Let me know if you need any further info!

**Comment by uncodead** [comment]
Thanks, mission acomplished.

But, i have some problem when i run interface:

![image](https://user-images.githubusercontent.com/181846/56853323-5a725380-68fc-11e9-8e37-1fe6fca7269a.png)

**Comment by uncodead** [comment]
Resolved upgrating npm/node. Thanks

**Comment by rjwats** [comment]
Thanks, glad you managed to fix the issue.
