### ISSUE TITLE
MQTT keep alive value of 16?

### ISSUE THREAD

**Issue by proddy** [rjwats/esp8266-react#176]
https://github.com/rjwats/esp8266-react/blob/6ef5df28c1bbca71dcfae42c8c8099764d1137f5/factory_settings.ini#L41

Is there a reason the MQTT keep alive is default to 16 seconds? Anything special about this value? I would think 30 or 60 seconds may be standard.

**Comment by rjwats** [comment]
No idea where a default of 16 came from perhaps from testing... 60 seconds
seems to be more natural

**Comment by rjwats** [comment]
Updated to 60 secs in the LittleFS branch, looks like this can get merged in now, fancy testing it?

Sadly there's a deprectaion warning still because of SPIFFSEditor in AsyncWebServer...
