### ISSUE TITLE
MQTT Homeassistant auto discovery

### ISSUE THREAD

**Issue by tichaonax** [rjwats/esp8266-react#178]
I followed the example for mqtt and homeassistant picks up my devices automatically. However this only happens if the topic has "light" as part of the topic. I want a Switch card. Everything with homeassistant/light/device is picked up and shows under Light card, homeassistant/switch/device does not, however both show up in MQTT. I want some devices to show under Switch card.

Am l doing something wrong.

**Comment by rjwats** [comment]
Quite possibly your topics aren't configured correctly for suto
discovery... have you got a link to the code?

**Comment by tichaonax** [comment]
The code can be found here. https://github.com/tichaonax/esp8266-react-scheduler
The two files with the implementation are:

esp8266-react-scheduler/src/automation/ChannelStateService.cpp
<img width="606" alt="image" src="https://user-images.githubusercontent.com/1031407/87880498-bde01980-c9b7-11ea-8095-e0852c40b401.png">
 and
esp8266-react-scheduler/src/automation/ChannelMqttSettingsService.h
<img width="937" alt="image" src="https://user-images.githubusercontent.com/1031407/87880540-0992c300-c9b8-11ea-93d0-713439fe82fc.png">

The MQTT has the two entries one for light and the other the switch they differ only on the switch but only the light is picked up by homeassistant. 

See the two entries below for 85b8f.
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/1031407/87880470-82dde600-c9b7-11ea-94f6-3a062379526c.png">

I looked in the example and even tried putting a number infront of the switch like "switch1" as part of the topic but its not picked. What is strange is that both topics are in the MQTT but only the lights show in homeassistant.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/1031407/87880651-ffbd8f80-c9b8-11ea-94b0-c4942868a72f.png">

**Comment by rjwats** [comment]
It doesn't look like switches support "schema":"json" as lights do...
probably because the payload is so simple for a switch - binary value only.

**Comment by rjwats** [comment]
https://www.home-assistant.io/docs/mqtt/discovery/#switches

Try poking this into your broker, it will work just fine i'm sure - adding
"schema":"json"  breaks it :)

**Comment by tichaonax** [comment]
That was it, I moved the light json statement into the case block and walla! my switch showed. Thanks again!
