### ISSUE TITLE
Question: how to implement a dynamic form

### ISSUE THREAD

**Issue by proddy** [rjwats/esp8266-react#180]
In my project I have a web table that's dynamically built with data from coming from the ESP, similar to the way the security form is done with username/admin's and rest interface. Now I'd like to be able to make the table selectable so when a row is clicked a separate form on the same page is dynamically loaded with specific data from the ESP. Can you suggest the best way to approach this? I'm a bit stuck here.

BTW the table currently looks like https://github.com/proddy/EMS-ESP/blob/v2/media/web_devices.PNG

**Comment by rjwats** [comment]
I'm assuming there is a key of some description in the data for each table
row which can be used as a basis for the rest request to load/save the
nested entity.

I would pass this key as a prop into a container which can load (save if
required) the nested data and have another nested component to render the
appropriate form.

There are some good example in this thread of how to make the table work
this way: https://github.com/mui-org/material-ui/issues/4476

**Comment by proddy** [comment]
Ah, I see. So refresh the whole form which contains the table and the other related information. I'll give that a go

**Comment by proddy** [comment]
implemented it, thanks for the idea.
