### ISSUE TITLE
question: is there call via the setting services to force a 'save' of the settings?

### ISSUE THREAD

**Issue by proddy** [rjwats/esp8266-react#182]
I wanted to be able to change the wifi username and password without immediately causing a Wifi reset, so using the `updateWithoutPropagation` function like:

```
:esp8266React.getWiFiSettingsService()->updateWithoutPropagation([&](WiFiSettings & wifiSettings) {
                                               wifiSettings.ssid = <new value here>
                                               return StateUpdateResult::CHANGED;
                                           });
```

Since none of the StatefulService registered update handlers are called I don't think the new setting values get persisted back in the FS? If correct is there a way to manually invoke a save?

**Comment by rjwats** [comment]
FSPersistence class exposes the writeToFS public function which you can
call to save the current state to the file system.

**Comment by proddy** [comment]
I couldn't get to the FSPersistence of the core services like Wifi, so did a work-around with
 `esp8266React.getWiFiSettingsService()->callUpdateHandlers("local"); ` which does the save.

**Comment by rjwats** [comment]
Yeah that's the best approach as long as you don't mind the other update
handlers also firing at the same time.
