### ISSUE TITLE
SPIFFS_write error(-10001): File system if full

### ISSUE THREAD

**Issue by justoke** [rjwats/esp8266-react#200]
I tried commenting out PROGMEM_WWW and building. Target device is ESP32. I get this error and if I upload it the UI is not available when the AP is presented.

Are SPIFFS still supported for hosting the UI or is PROGMEM_WWW recommended?

![image](https://user-images.githubusercontent.com/26506785/97816595-3d0b0c00-1c8e-11eb-96bc-366774fce4de.png)

Thank you.

**Comment by justoke** [comment]
I forgot about min_spiffs.csv!

**Comment by rjwats** [comment]
Yup - well spotted.
