### ISSUE TITLE
How can I use interrupts

### ISSUE THREAD

**Issue by fgbs** [rjwats/esp8266-react#240]
How can I use interrupts to detect changes in sensors like PIR to update state events??

**Comment by rjwats** [comment]
I guess you are best off looking at a generic arduino pin-change interrupt example:

https://lastminuteengineers.com/handling-esp32-gpio-interrupts-tutorial/#:~:text=ESP32%20GPIO%20Interrupt,function%20as%20interrupt%20request%20inputs.

When the change is detected, you can raise the state update as shown in [this section](https://github.com/rjwats/esp8266-react#stateful-service) of the documentation.
