### ISSUE TITLE
MQTT Settings restricts Host name to 32 characters

### ISSUE THREAD

**Issue by justoke** [rjwats/esp8266-react#249]
The MQTT settings form validates the Host based on a regex and length check. This has never been an issue until just recently when  I hosted an MQTT broker on an Azure container which resulted in a host name with more than 32 characters.

![image](https://user-images.githubusercontent.com/26506785/122727539-0a3e7400-d26f-11eb-9928-998ba3b83dd0.png)

![image](https://user-images.githubusercontent.com/26506785/122727153-a3b95600-d26e-11eb-8b96-954cccfd3e36.png)

I see no technical reason for the restriction and assume this was probably a reused bit of validation. As this is easily overcome, treat this as an FYI.

**Comment by rjwats** [comment]
Yes, I'm not sure why this restriction was put in either.

Hostnames segments (I think they are called 'labels') have a max length of 63 characters, though the full hostname can be up to 253 characters (according to linux manual. I'll update the regex.

**Comment by justoke** [comment]
Thank you for sweeping this one up.
