### ISSUE TITLE
More elaborated dashboard

### ISSUE THREAD

**Issue by uncodead** [rjwats/esp8266-react#26]
Hi, I would like to create a more elaborate dashboard for my application, with some gadget like the image below. My question is: with your experience with the framework, what is the best approach to elaborate a dashboard like this maintaining all the characteristics of the framework?

![image](https://user-images.githubusercontent.com/181846/58120150-0268fd00-7bdb-11e9-97b6-95561db09066.png)

**Comment by rjwats** [comment]
This is an exercise for the reader really as it will depend on your use case :)

I have had decent success with the react wrapper for jschart2 for charts:

https://github.com/jerairrest/react-chartjs-2

I've used this on my [fermenator project](https://github.com/rjwats/esp8266-react/tree/fermentation-chamber) with good results. 

I'd be inclined to use [the grid](https://material-ui.com/layout/grid/) to ensure you get good fluid UI when using it on a mobile device or desktop.

Good luck!

**Comment by uncodead** [comment]
Thanks! 

![image](https://user-images.githubusercontent.com/181846/58275489-86ea8580-7d6b-11e9-88ec-fdb08a8702ef.png)
