### ISSUE TITLE
Water flow meter  loop and mqtt implementation 

### ISSUE THREAD

**Issue by moayyaed** [rjwats/esp8266-react#261]
how I can implement water flow sensor using MQTT?
In my case i have water pump and water flow meter,so i have to turn water pump like the light demo project but i need to start reading the water flow amount and publish it to mqtt broker  until turn bump off ,and i want to read the flow amount using web socket.

**Comment by rjwats** [comment]
The demo app is configured to do something similar to this, see the docs for more details on how to use MQTT:

https://github.com/rjwats/esp8266-react#mqtt

**Comment by moayyaed** [comment]
Thank rjwats for your feedback ,i think my questions was not clear so please if you find it still not clear i will explain in detail.
