### ISSUE TITLE
Overriding authentication functions

### ISSUE THREAD

**Issue by tichaonax** [rjwats/esp8266-react#269]
I need to override some functions in the file ```interface\src\api\authentication.ts```

specifically the following function.
```
export function getStorage() {
  return localStorage || sessionStorage;
}
```

I want the function to check if remote device configuration is required if so then get the authentication from the remote device but do not store it else its local device proceed as before. I had the code working before by making changes to the framework but I want to avoid that.

Do you have any ideas of how I could achieve the same not necessarily the way I am suggesting. I just want to authenticate against the remote device if remote configuration is detected

**Comment by rjwats** [comment]
At this point, without really knowing all the details of you're trying to
do, it's hard to say.  I would suggest doing whatever is needed to get it
working initially.

I'm happy to review code and make suggestions once it's written if it's
helpful to you.

I also don't think you should be too afraid of making small changes to the
framework code - you are probably a "power user" by now.
