### ISSUE TITLE
Build error on windows

### ISSUE THREAD

**Issue by uncodead** [rjwats/esp8266-react#27]
I have a windows dev environment and when i build the framework i get this error:
![image](https://user-images.githubusercontent.com/181846/58724249-79a84900-83b2-11e9-9f22-b7925b3db43f.png)
So, i need to rename the time.h file and rename at this line:
![image](https://user-images.githubusercontent.com/181846/58724090-1ae2cf80-83b2-11e9-8e3c-ab3de296587d.png)
Because windows is not case sensitive. What's the best way to avoid this problem?

**Comment by rjwats** [comment]
See the comment in the documentation regarding this issue under windows. I've not found a better solution but am going to investigate a pre-build python script to allow for the

**Comment by uncodead** [comment]
Yes, I followed this post to solve the problem. But it's not good for users to make this rack on their machine

**Comment by rjwats** [comment]
Not ideal, but neither is forking or copying the time library to delete the file. Like I say - i think a pre-build script is probably the easiest solution which will resolve the issue at build time. Will get to this at some point - currently working on [adding security](https://github.com/rjwats/esp8266-react/pull/29).

**Comment by rjwats** [comment]
I've developed a solution which should resolve this issue at build time, it involves a pre-build script which deletes the offending Time.h file before the build begins:

[timelib_fix.py](https://github.com/rjwats/esp8266-react/blob/master/timelib_fix.py)

Looks like this works on fresh builds on my windows box, let me know how this works for you.

**Comment by uncodead** [comment]
It works, thanks
