### ISSUE TITLE
NTP server not reachable

### ISSUE THREAD

**Issue by uncodead** [rjwats/esp8266-react#28]
At startup my esp8266 get sincronized with NTP server (Got NTP time: ...). After some attempts i get the error (NTP server not reachable). My question is: after the first sincronization do i need to care about time? The time will be unsynchronized? Thanks

**Comment by rjwats** [comment]
NTP uses UDP and has not got the same QoS guarantees of a TCP based service so failure messages should be expected. The time library will retry with a back-off approach IIRC - I wouldn't worry about this issue unless it's not ever synchronizing successfully (which would more likely indicate a network or server issue). I'm going to be modifying the default synchronization interval - the current default of 60 seconds is far too aggressive the expected drift associated with these devices (~a few seconds per day)

**Comment by uncodead** [comment]
Thanks
