### ISSUE TITLE
MQTT retained message

### ISSUE THREAD

**Issue by thisiscam** [rjwats/esp8266-react#287]
Hi,

I'm wondering if we can add the retained option to a MQTT publish? Perhaps with a flag to for each MQTTPubSub?

See: https://github.com/rjwats/esp8266-react/blob/master/lib/framework/MqttPubSub.h#L67

**Comment by rjwats** [comment]
Yes, that sounds sensible because it's a per-topic setting. I'll be working
on the project a bit this weekend and can tackle that then.

**Comment by rjwats** [comment]
https://github.com/rjwats/esp8266-react/pull/288

Does this look like it will do what you want?

**Comment by thisiscam** [comment]
LGTM!
