### ISSUE TITLE
How run commands when updating time ?

### ISSUE THREAD

**Issue by spyflox** [rjwats/esp8266-react#296]
Hello everyone,

I would like to update my RTC clock when the user changes the time manually or the time is automaticaly set buy NTP.

It would be ideal for me to be able to add some code when the `NTPSettingsService::configureTime` function is called. Is there already a handler on this? If not,  what can I do if I don't want to touch the framework code directly?

**Comment by FernandoGarcia** [comment]
Hi! 

I think doesn't exits a function inside of any esp8266React class.

The easiest way to get the current time and configure the RTC is:

```cpp
time_t tnow = time(nullptr);
rtc.SetDateTime(tnow);
```

The way how the new date and time is saved to RTC changes from library to library. 

You have to adjust according to the library that are you using.

`tnow` value in this case is an unix time.

Best regards.
