### ISSUE TITLE
Error npm start or build  Error: ...API schema.  - options.allowedHosts[0] should be a non-empty string.

### ISSUE THREAD

**Issue by benn87** [rjwats/esp8266-react#300]
npm start 

the result is.
> esp8266-react@0.1.0 start
> react-app-rewired start

Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.allowedHosts[0] should be a non-empty string.

What is it?

**Comment by rjwats** [comment]
Not somthing I've seen before... have you done "npm install" or "npm ci" first?

What version of node/npm are you using?

**Comment by rjwats** [comment]
ok, thanks

**Comment by mareerste** [comment]
In the root of your ReactApp folder, if you haven't already, create '.env' file and add:
DANGEROUSLY_DISABLE_HOST_CHECK=true

This could be used for development environment but should not be used in production!
