### ISSUE TITLE
Wemos reseting

### ISSUE THREAD

**Issue by uncodead** [rjwats/esp8266-react#52]
Hello! How are you? I hope you are good!

I'm facing some erros on my project. My wemos get rebooted when i reload the interface. I think my interface has a 330kb compacted js. And this take overhead on ESP.

Do yout know if i can chunk more than 3 js.gz with webpack?

**Comment by rjwats** [comment]
You'll probably already be aware that the project uses  react-app-rewired
<https://github.com/timarney/react-app-rewired> to customise the build for
the SPIFFS file system limitations
<https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html#spiffs-file-system-limitations>,
this is using the config-overrides.js
<https://github.com/rjwats/esp8266-react/blob/master/interface/config-overrides.js>
 file.

You should be able to customise the chunking with the webpack optimiser,
(configuring it in config-overrides.js):

https://medium.com/hackernoon/the-100-correct-way-to-split-your-chunks-with-webpack-f8a9df5b7758
