### ISSUE TITLE
Add Blynk to project

### ISSUE THREAD

**Issue by khoazero123** [rjwats/esp8266-react#54]
Hi, I'm trying to add Blynk to this project but get this error: 
`multiple definition of Blynk`

![image](https://user-images.githubusercontent.com/2802354/68741178-8c8c9e00-061f-11ea-94a8-76225097dff3.png)

Can someone help me fix this?

**Comment by rjwats** [comment]
Sorry I didn't respond at the time. If you still need help with this, feel free to re-open.
