### ISSUE TITLE
PlatformIO 4.x environment settings changed

### ISSUE THREAD

**Issue by proddy** [rjwats/esp8266-react#56]
On my win10 environmment, PlatformIO uses different environment variables, so to build the firmware I had to change `PROJECTLIBDEPS_DIR` to  `PROJECT_LIBDEPS_DIR` in the file `timelib_fix.py`.

To reproduce delete .pio folder and re-build. I used `print(env.Dump())` in the script to find the right variable to use.

**Comment by rjwats** [comment]
Thanks for reporting this Proddy.

Will take a look shortly, and write a backwards-compatible fix.

Rick

**Comment by rjwats** [comment]
Merged a fix for this this morning, please can you verify it works for you?

**Comment by proddy** [comment]
confirmed build works again. thanks
