### ISSUE TITLE
Support ArduinoJson 6.x.x

### ISSUE THREAD

**Issue by rjwats** [rjwats/esp8266-react#6]
The latest versions of ArduinoJson (6.0.0+) have some fairly significant changes requiring migration:

https://arduinojson.org/v6/doc/upgrade/?utm_source=github&utm_medium=release

**Comment by atsteen** [comment]
Thank you sir!  Let us know if you want some extra eyes on this, glad to help if I can.

**Comment by rjwats** [comment]
https://github.com/rjwats/esp8266-react/pull/8/files

Monkey tested and load tested with SoapUI on esp32 and esp8266 cores. Any comments welcome!
